// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTransfer = "transfers"

// Transfer mapped from table <transfers>
type Transfer struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	FromAccountID int64     `gorm:"column:from_account_id;not null" json:"from_account_id"`
	ToAccountID   int64     `gorm:"column:to_account_id;not null" json:"to_account_id"`
	Account       int64     `gorm:"column:account;not null" json:"account"`
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
}

// TableName Transfer's table name
func (*Transfer) TableName() string {
	return TableNameTransfer
}
